apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.sockshop1-staging.20.198.138.61.nip.io
  - carts
  http:
  - route:
    - destination:
        host: carts-canary.sockshop1-staging.svc.cluster.local
    - destination:
        host: carts-primary.sockshop1-staging.svc.cluster.local
      weight: 100
