apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.sockshop1-dev.20.198.138.61.nip.io
  - carts
  http:
  - route:
    - destination:
        host: carts.sockshop1-dev.svc.cluster.local
